### ISSUE TITLE
pkgconfig file name with version issue

### ISSUE THREAD

**Issue by ye-luo** [marekandreas/elpa#3]
Currently elpa installation adds
```
lib/libelpa.so
lib/pkgconfig/elpa-2020.05.001.pc
```
files.

When I use `pkg_search_module` in CMake to look for `elpa`, it searches for elpa.pc but doesn't recognize `elpa-VERSION.pc`, then I got a chicken and egg problem. I can only search with the version but If I don't find elpa, how do I know the version.

I'd like to see how other people solves this issue.
Or can we just put elpa.pc wthout VERSION.

**Comment by marekandreas** [comment]
On many HPC centers several different versions of ELPA are installed at the same time, and thus I'd rather keep the elpa-VERSION.pc. Normally, we assume user know which version they would like to use, since  the load a specific module (via the HPC module environment system which is nowadays on every HPC system installed). But I agree on a non-HPC system the situation might be different. Have to think about this...

**Comment by marekandreas** [comment]
The pkgconfig-file will be rename to `elpa.pc` in the next release.

**Comment by ye-luo** [comment]
@marekandreas did you mean ELPA 2021.11.001 which is rc1 or 2022?
