### ISSUE TITLE
Checking configure option to disable non-implemented gpuBLAS with redistribute matrix

### ISSUE THREAD

**Issue by yizeyi18** [marekandreas/elpa#43]
According to src/elpa1/elpa1_template.F90, line 386, gpuBLAS with redistribute matrix is not implemented; trying to use so would result in memcopy issue and fall in segmentation fault. Is it possible checking configure option in release to disable that at configure stage instead of during testing?

**Comment by marekandreas** [comment]
Dear @yizeyi18,

hmm. I have first to understand what is going on here. Disabling at configure-time would not be an option, since it is perfectly valid to build the GPU version, but only run the CPU version (decision at run-time) and to use matrix re-distribution. In deed, matrix re-distribution should work with GPUs! We will fix this asap

**Comment by marekandreas** [comment]
Dear @yizeyi18 ,

sorry for the delay, but this has been implemented now for ELPA 1 stage. This will be available in the next release coming up in the next 2-3 weeks. For ELPA 2 stage this will be implemented now, but might not make it into the next release

**Comment by yizeyi18** [comment]
@marekandreas Great. Waiting for its release.
