### ISSUE TITLE
I can use ELPA when no_procs > matrix size

### ISSUE THREAD

**Issue by TomMelt** [marekandreas/elpa#9]
Hi,

Question
------------

Is it possible to use `ELPA` for small matrices when the number of mpi processes n_procs is larger than the number of elements in the matrix?

Explanation of situation
-------------------------------
For practical purposes I would sometimes like to use more processes than the size of my matrix.

Currently, we can use `ELPA` or `ScaLAPACK` to diagonalise all of the matrices in our code. The first one can be very small but the second is typically 10,000 x 10,000.

For example, if the first matrix is 2x2 and I use 8 or more processes then calculations fails using ELPA. But if I use ScaLAPACK it will run.

For practical reasons I cannot share the code but both ScaLAPACK and ELPA runs use the same grid setup using `BLACS_Gridinit` and `descinit` etc.

Is there a simple explanation to this? 

The errors/warning I get for the 2x2 matrix with 8 procs are:
```
 ELPA: Warning, block size too large for this matrix size and process grid!
 Choose a smaller block size if possible.
```
All the `success` points are checked, including elpa%setup() and it fails when the `success` returned by elpa%eigenvectors is not equal to `elpa_OK`.

As for a 1x1 matrix (running with 2 procs) I get a different error:
```
 ELPA_SETUP ERROR: your provided blacsgrid is not ok! 
 BLACS_GRIDINFO returned an error! Aborting...
```

I know it may seem stupid to use ELPA for 1x1 matrix but it is more that the code is structured to use 1 diagonaliser for everything. Using ScaLAPACK we can do this but it appears ELPA has different criteria.

I can possibly implement a workaround to deal with small matrices but I'd prefer to make minimal changes.

Elpa version is: `2021.05.002`
I use tried two intel compilers: `19.0.0.117 20180804` and `2021.4.0 20210910`

Sorry if this is too vague. I guess my main question is not how do you specifically fix my problem but is it in principle possible to use ELPA for small matrices when the number of mpi processes n_procs is large.

**Comment by marekandreas** [comment]
In short: no you cannot do this. Here is why: 
`blacs_grid_info` does return an `info` value. For any value != 0, this indicates that the Blacs-grid has not been set up successfully. Since the algorithms in ELPA do rely on a correct Blacs-grid, you can run into the error messages you quoted, if your combination of matrix size, block size and process grid does not return `info = 0` in blacs_grid_info.
I do agree, that with ScaLapack this might still work, since ScaLapack might be able to work with an "uncorrect" Blacs-grids, ELPA however does not.
I dare speculate, however, that in the cases where ELPA does return the error messages from above, but ScaLapack on the other hand runs successfully, that the `info` return code !=0 (i.e. not correct blacs setup).

However, there is a way to solve this with ELPA: 
- ELPA does allow you to create multiple solver objects, and
- you can create sub-MPI-communicators (MPI_COMM_SPLIT) , such that the number of MPI processes chosen does allow a correct (info=0) blacs initialization.
So you could create several sub-communicators , and with these create several ELPA objects, and use the correct communicator (ELPA object) depending on the matrix size.

Concerning the 1x1 matrix: I admit this is not implemented in ELPA at all (but could be special cased)

**Comment by TomMelt** [comment]
Awesome. Thanks for your suggestions. I thought I was going crazy.

I admit 1x1 matrix is not the target audience of a highly parallel diagonalizer. 

I will take a look at the sub-MPI communicators as recommended and potentially we will just modify the code to use a serial diagonalizer for small matrix where `no_elems < n_procs`

**Comment by TomMelt** [comment]
I will close this "issue". Thanks for your help.
